#pragma once

// Mouse buttons codes from GLFW
#define EUCLEDIA_MOUSE_BUTTON_1         0
#define EUCLEDIA_MOUSE_BUTTON_2         1
#define EUCLEDIA_MOUSE_BUTTON_3         2
#define EUCLEDIA_MOUSE_BUTTON_4         3
#define EUCLEDIA_MOUSE_BUTTON_5         4
#define EUCLEDIA_MOUSE_BUTTON_6         5
#define EUCLEDIA_MOUSE_BUTTON_7         6
#define EUCLEDIA_MOUSE_BUTTON_8         7
#define EUCLEDIA_MOUSE_BUTTON_LAST      EUCLEDIA_MOUSE_BUTTON_8
#define EUCLEDIA_MOUSE_BUTTON_LEFT      EUCLEDIA_MOUSE_BUTTON_1
#define EUCLEDIA_MOUSE_BUTTON_RIGHT     EUCLEDIA_MOUSE_BUTTON_2
#define EUCLEDIA_MOUSE_BUTTON_MIDDLE    EUCLEDIA_MOUSE_BUTTON_3