Scene: Untitled
Entities:
  - Entity: 1
    TagComponent:
      Tag: Green Square
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteRendererComponent:
      Color: [0, 1, 0, 1]
  - Entity: 1
    TagComponent:
      Tag: Camera A Entity
    TransformComponent:
      Translation: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      Camera:
        ProjectionType: 1
        perspectiveFOV: 0.7853982
        PerspectiveNearClip: 0.01
        PerspectiveFarClip: 1000
        OrthographicSize: 10
        OrthographicNearClip: -1
        OrthographicFarClip: 1
      Primary: true
      FixedAspectRatio: false
  - Entity: 1
    TagComponent:
      Tag: Red Square
    TransformComponent:
      Translation: [0.7, 0.6, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteRendererComponent:
      Color: [1, 0, 0, 1]